(() => {
'use strict';

const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const clamp=(v,min=0,max=255)=>v<min?min:v>max?max:v;
const sleep=()=>new Promise(r=>setTimeout(r,0));
const fmtBytes=n=>{const u=['B','KB','MB','GB'];let i=0;while(n>=1024&&i<u.length-1){n/=1024;i++}return `${n.toFixed(i?1:0)} ${u[i]}`};
const baseName=n=>n.replace(/\.[^.]+$/,'');
const uid=()=>crypto.randomUUID?crypto.randomUUID():`${Date.now()}-${Math.random()}`;
const cloneCanvas=src=>{const c=document.createElement('canvas');c.width=src.width;c.height=src.height;c.getContext('2d').drawImage(src,0,0);return c};

const state={jobs:[],currentId:null,zoom:'fit',busy:false,history:[],safeMaxPixels:70_000_000,safeMaxDimension:16384,tool:'none',cloneSource:null,stroke:null,customPreset:null};
const els={
  dropzone:$('#dropzone'),fileInput:$('#fileInput'),pickFiles:$('#pickFiles'),jobList:$('#jobList'),clearJobs:$('#clearJobs'),
  currentName:$('#currentName'),currentMeta:$('#currentMeta'),compareStage:$('#compareStage'),canvasScroller:$('#canvasScroller'),compareWrap:$('#compareWrap'),
  before:$('#beforeCanvas'),after:$('#afterCanvas'),afterClip:$('#afterClip'),divider:$('#divider'),compareSlider:$('#compareSlider'),histogram:$('#histogram'),
  statusText:$('#statusText'),progressBar:$('#progressBar'),analysisText:$('#analysisText'),warningText:$('#warningText'),printInfo:$('#printInfo'),compatInfo:$('#compatInfo'),
  runAuto:$('#runAuto'),runBatch:$('#runBatch'),resetCurrent:$('#resetCurrent'),undo:$('#undoBtn'),redo:$('#redoBtn'),
  exportFormat:$('#exportFormat'),exportQuality:$('#exportQuality'),exportDpi:$('#exportDpi'),exportCurrent:$('#exportCurrent'),exportZip:$('#exportZip'),downloadOriginal:$('#downloadOriginal'),exportNotice:$('#exportNotice')
};

const adjustmentIds=['exposure','brightness','contrast','highlights','shadows','whites','blacks','gamma','whiteStrength','temperature','tint','hue','vibrance','saturation','denoise','sharpen','clarity','dehaze','blur','vignette','grain','pixelate'];
for(const id of adjustmentIds.concat(['bgTolerance','brushSize','brushHardness'])){
  const i=$('#'+id),o=$('#'+id+'Out'); if(i&&o) i.addEventListener('input',()=>o.textContent=id==='gamma'?Number(i.value).toFixed(2):id==='hue'?`${i.value}°`:i.value);
}

const presets={
  customer:{mode:'ai',exposure:0,brightness:0,contrast:10,highlights:-4,shadows:5,whites:0,blacks:0,gamma:1,whiteStrength:78,temperature:-3,tint:0,hue:0,vibrance:24,saturation:6,denoise:10,sharpen:32,clarity:8,dehaze:3,blur:0,vignette:0,grain:0,pixelate:0,upscale:2},
  product:{mode:'product',exposure:.1,brightness:2,contrast:12,highlights:-8,shadows:7,whites:8,blacks:-3,gamma:1,whiteStrength:92,temperature:-2,tint:0,hue:0,vibrance:16,saturation:2,denoise:6,sharpen:38,clarity:12,dehaze:4,blur:0,vignette:0,grain:0,pixelate:0,upscale:2},
  portrait:{mode:'portrait',exposure:.05,brightness:1,contrast:5,highlights:-12,shadows:10,whites:2,blacks:1,gamma:1,whiteStrength:58,temperature:1,tint:1,hue:0,vibrance:10,saturation:0,denoise:18,sharpen:18,clarity:-6,dehaze:0,blur:0,vignette:-8,grain:0,pixelate:0,upscale:2},
  graphic:{mode:'graphic',exposure:0,brightness:0,contrast:18,highlights:0,shadows:0,whites:8,blacks:-8,gamma:1,whiteStrength:88,temperature:0,tint:0,hue:0,vibrance:6,saturation:0,denoise:0,sharpen:48,clarity:16,dehaze:2,blur:0,vignette:0,grain:0,pixelate:0,upscale:2},
  print:{mode:'photo',exposure:0,brightness:0,contrast:8,highlights:-6,shadows:6,whites:2,blacks:-2,gamma:1,whiteStrength:72,temperature:-2,tint:0,hue:0,vibrance:18,saturation:3,denoise:8,sharpen:38,clarity:10,dehaze:2,blur:0,vignette:0,grain:0,pixelate:0,upscale:4},
  web:{mode:'photo',exposure:0,brightness:0,contrast:8,highlights:-3,shadows:4,whites:0,blacks:0,gamma:1,whiteStrength:62,temperature:-1,tint:0,hue:0,vibrance:16,saturation:3,denoise:6,sharpen:24,clarity:5,dehaze:0,blur:0,vignette:0,grain:0,pixelate:0,upscale:1},
  bw:{mode:'graphic',exposure:0,brightness:0,contrast:22,highlights:-3,shadows:3,whites:8,blacks:-10,gamma:1,whiteStrength:0,temperature:0,tint:0,hue:0,vibrance:0,saturation:-100,denoise:4,sharpen:40,clarity:18,dehaze:5,blur:0,vignette:0,grain:0,pixelate:0,upscale:2},
  upscale:{mode:'graphic',exposure:0,brightness:0,contrast:0,highlights:0,shadows:0,whites:0,blacks:0,gamma:1,whiteStrength:0,temperature:0,tint:0,hue:0,vibrance:0,saturation:0,denoise:0,sharpen:0,clarity:0,dehaze:0,blur:0,vignette:0,grain:0,pixelate:0,upscale:4}
};

function setStatus(t,p=0){els.statusText.textContent=t;els.progressBar.style.width=`${clamp(p,0,100)}%`}
function currentJob(){return state.jobs.find(j=>j.id===state.currentId)||null}
function warn(job,msg){if(msg&&!job.warnings.includes(msg))job.warnings.push(msg)}
function showWarnings(job){els.warningText.textContent=job?.warnings?.length?`Hinweise:\n${job.warnings.map(x=>'• '+x).join('\n')}`:''}
function setBusy(v){state.busy=v;[els.runAuto,els.runBatch,els.exportCurrent,els.exportZip].forEach(b=>{if(b)b.disabled=v})}
function escapeHtml(s){return String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}

function compatibility(){
  const mem=Number(navigator.deviceMemory||8);state.safeMaxPixels=mem<=4?30_000_000:mem<=6?45_000_000:70_000_000;
  els.compatInfo.textContent=[`RAM-Profil: ~${mem} GB`,`HEIC: ${window.heic2any?'ja':'nein'}`,`TIFF: ${window.UTIF&&window.pako?'ja':'nein'}`,`ZIP: ${window.JSZip?'ja':'nein'}`,`FaceDetector: ${'FaceDetector'in window?'ja':'nein'}`].join(' • ');
}
window.addEventListener('load',compatibility);

$$('.tab').forEach(b=>b.onclick=()=>{const n=b.dataset.tab;$$('.tab').forEach(x=>x.classList.toggle('active',x===b));$$('.tabpane').forEach(p=>p.classList.toggle('active',p.dataset.pane===n))});
$$('.preset').forEach(b=>b.onclick=()=>applyPreset(b.dataset.preset));
function applyPreset(name){const p=presets[name];if(!p)return;for(const[k,v]of Object.entries(p)){const el=$('#'+k);if(!el)continue;el.value=v;const out=$('#'+k+'Out');if(out)out.textContent=k==='gamma'?Number(v).toFixed(2):k==='hue'?`${v}°`:v}$$('.preset').forEach(x=>x.classList.toggle('active',x.dataset.preset===name));setStatus(`Preset „${bName(name)}“ geladen.`,0)}
function bName(n){return({customer:'Auto Kundenfertig',product:'Produkt Clean',portrait:'Portrait',graphic:'Grafik/Text',print:'Print 300 DPI',web:'Web',bw:'S/W Clean',upscale:'Nur Upscale'})[n]||n}

els.pickFiles.onclick=()=>els.fileInput.click();
els.fileInput.onchange=async e=>{await addFiles([...e.target.files]);e.target.value=''};
['dragenter','dragover'].forEach(ev=>els.dropzone.addEventListener(ev,e=>{e.preventDefault();els.dropzone.classList.add('drag')}));
['dragleave','drop'].forEach(ev=>els.dropzone.addEventListener(ev,e=>{e.preventDefault();els.dropzone.classList.remove('drag')}));
els.dropzone.addEventListener('drop',e=>addFiles([...e.dataTransfer.files]));
els.dropzone.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();els.fileInput.click()}});

async function addFiles(files){files=files.filter(f=>f&&f.size>0);if(!files.length)return setStatus('Keine gültigen Dateien.',0);for(const file of files){state.jobs.push({id:uid(),file,name:file.name,size:file.size,type:file.type||'unbekannt',original:null,working:null,analysis:null,warnings:[],progress:0,status:'geladen',history:[],historyIndex:-1,created:new Date()})}if(!state.currentId)state.currentId=state.jobs[0].id;renderJobs();await selectJob(state.currentId)}
function renderJobs(){if(!state.jobs.length){els.jobList.innerHTML='<div class="empty-state">Noch keine Bilder geladen.</div>';return}els.jobList.innerHTML='';for(const j of state.jobs){const d=document.createElement('div');d.className='job-item'+(j.id===state.currentId?' active':'');d.dataset.id=j.id;d.innerHTML=`<strong>${escapeHtml(j.name)}</strong><span>${fmtBytes(j.size)} • ${escapeHtml(j.status)}${j.warnings.length?` • <b class="warn">${j.warnings.length} Hinweis${j.warnings.length>1?'e':''}</b>`:''}</span><div class="job-progress"><i style="width:${j.progress}%"></i></div>`;d.onclick=()=>selectJob(j.id);els.jobList.appendChild(d)}}
async function selectJob(id){state.currentId=id;renderJobs();const j=currentJob();if(!j)return;els.currentName.textContent=j.name;els.currentMeta.textContent=`${fmtBytes(j.size)} • ${j.type}`;try{await ensureDecoded(j);drawComparison(j);analyzeAndShow(j);showWarnings(j);syncGeometryFields(j);updateHistoryButtons()}catch(e){j.status='Fehler';warn(j,e.message);renderJobs();showWarnings(j);setStatus(`Fehler: ${e.message}`,0)}}

async function ensureDecoded(j){if(j.original)return j.original;setStatus(`Dekodiere ${j.name} …`,5);const d=await decodeFile(j.file);try{if(!d.width||!d.height)throw new Error('Ungültige Bildgröße.');if(d.width>state.safeMaxDimension||d.height>state.safeMaxDimension)throw new Error(`Bildkante ${d.width}×${d.height}px überschreitet das sichere Browser-Limit.`);const c=document.createElement('canvas');c.width=d.width;c.height=d.height;const x=c.getContext('2d',{willReadFrequently:true});if(!x)throw new Error('Kein 2D-Canvas verfügbar.');x.drawImage(d.source,0,0);j.original=c;j.working=cloneCanvas(c);j.analysis=analyzeCanvas(c);j.status='bereit';j.progress=10;pushHistory(j,'Original',true);if(/\.gif$/i.test(j.name))warn(j,'Animierte GIFs werden als erster Frame bearbeitet.');renderJobs();return c}finally{d.cleanup?.()}}
async function decodeFile(file){const ext=(file.name.split('.').pop()||'').toLowerCase();if(['heic','heif'].includes(ext)){if(!window.heic2any)throw new Error('HEIC/HEIF-Decoder nicht geladen.');const blob=await heic2any({blob:file,toType:'image/png',quality:1});return decodeBlob(Array.isArray(blob)?blob[0]:blob)}if(['tif','tiff'].includes(ext)){if(!window.UTIF||!window.pako)throw new Error('TIFF-Decoder/Pako nicht geladen.');const buf=await file.arrayBuffer(),ifds=UTIF.decode(buf);if(!ifds.length)throw new Error('TIFF enthält kein lesbares Bild.');UTIF.decodeImage(buf,ifds[0]);const rgba=UTIF.toRGBA8(ifds[0]),c=document.createElement('canvas');c.width=ifds[0].width;c.height=ifds[0].height;c.getContext('2d').putImageData(new ImageData(new Uint8ClampedArray(rgba),c.width,c.height),0,0);return{width:c.width,height:c.height,source:c}}return decodeBlob(file)}
async function decodeBlob(blob){if('createImageBitmap'in window){try{const bm=await createImageBitmap(blob,{imageOrientation:'from-image',premultiplyAlpha:'default',colorSpaceConversion:'default'});return{width:bm.width,height:bm.height,source:bm,cleanup:()=>bm.close()}}catch{}}const url=URL.createObjectURL(blob),img=new Image();await new Promise((res,rej)=>{img.onload=res;img.onerror=()=>rej(new Error('Format wird von diesem Browser nicht dekodiert.'));img.src=url});return{width:img.naturalWidth,height:img.naturalHeight,source:img,cleanup:()=>URL.revokeObjectURL(url)}}

function pushHistory(j,label,force=false){if(!j.working)return;const px=j.working.width*j.working.height,max=px>25_000_000?4:px>12_000_000?6:10;if(!force&&j.historyIndex>=0&&j.history[j.historyIndex]?.label===label)return;j.history=j.history.slice(0,j.historyIndex+1);j.history.push({canvas:cloneCanvas(j.working),label});while(j.history.length>max)j.history.shift();j.historyIndex=j.history.length-1;updateHistoryButtons();addSessionHistory(j,label)}
function undo(){const j=currentJob();if(!j||j.historyIndex<=0)return;j.historyIndex--;j.working=cloneCanvas(j.history[j.historyIndex].canvas);afterMutation(j,`Undo: ${j.history[j.historyIndex].label}`,false)}
function redo(){const j=currentJob();if(!j||j.historyIndex>=j.history.length-1)return;j.historyIndex++;j.working=cloneCanvas(j.history[j.historyIndex].canvas);afterMutation(j,`Redo: ${j.history[j.historyIndex].label}`,false)}
function updateHistoryButtons(){const j=currentJob();els.undo.disabled=!j||j.historyIndex<=0;els.redo.disabled=!j||j.historyIndex>=j.history.length-1}
els.undo.onclick=undo;els.redo.onclick=redo;
window.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&!e.shiftKey&&e.key.toLowerCase()==='z'){e.preventDefault();undo()}else if((e.ctrlKey||e.metaKey)&&(e.key.toLowerCase()==='y'||(e.shiftKey&&e.key.toLowerCase()==='z'))){e.preventDefault();redo()}});

function drawComparison(j,full=true){if(!j?.working)return;const w=j.working.width,h=j.working.height;els.before.width=w;els.before.height=h;els.after.width=w;els.after.height=h;const bx=els.before.getContext('2d'),ax=els.after.getContext('2d');bx.clearRect(0,0,w,h);ax.clearRect(0,0,w,h);bx.drawImage(j.original,0,0,j.original.width,j.original.height,0,0,w,h);ax.drawImage(j.working,0,0);els.canvasScroller.hidden=false;els.compareStage.classList.remove('empty');const ep=els.compareStage.querySelector('.empty-preview');if(ep)ep.style.display='none';els.compareSlider.disabled=false;applyZoom();updateCompare();if(full){drawHistogram(j.working);updatePrintInfo(j.working.width,j.working.height)}}
function applyZoom(){const j=currentJob();if(!j?.working)return;let scale=1;if(state.zoom==='fit'){const maxW=Math.max(280,els.compareStage.clientWidth-40),maxH=570;scale=Math.min(1,maxW/j.working.width,maxH/j.working.height)}else scale=Number(state.zoom);const w=Math.max(1,Math.round(j.working.width*scale)),h=Math.max(1,Math.round(j.working.height*scale));els.compareWrap.style.width=w+'px';els.compareWrap.style.height=h+'px';[els.before,els.after].forEach(c=>{c.style.width=w+'px';c.style.height=h+'px'})}
$$('.zoom-btn').forEach(b=>b.onclick=()=>{state.zoom=b.dataset.zoom;$$('.zoom-btn').forEach(x=>x.classList.toggle('active',x===b));applyZoom()});window.addEventListener('resize',()=>{if(state.zoom==='fit')applyZoom()});
els.compareSlider.oninput=updateCompare;function updateCompare(){const v=Number(els.compareSlider.value);els.afterClip.style.clipPath=`inset(0 ${100-v}% 0 0)`;els.divider.style.left=v+'%'}

function analyzeCanvas(canvas){const ow=canvas.width,oh=canvas.height,scale=Math.min(1,900/Math.max(ow,oh),Math.sqrt(600000/(ow*oh))),w=Math.max(1,Math.round(ow*scale)),h=Math.max(1,Math.round(oh*scale)),s=document.createElement('canvas');s.width=w;s.height=h;const x=s.getContext('2d',{willReadFrequently:true});x.drawImage(canvas,0,0,w,h);const d=x.getImageData(0,0,w,h).data,hist=new Uint32Array(256);let n=0,sum=0,sum2=0,wr=0,wg=0,wb=0,wc=0,warm=0;for(let i=0;i<d.length;i+=4){if(d[i+3]<16)continue;const r=d[i],g=d[i+1],b=d[i+2],mx=Math.max(r,g,b),mn=Math.min(r,g,b),l=Math.round(.2126*r+.7152*g+.0722*b);hist[l]++;n++;sum+=l;sum2+=l*l;const chrom=(mx-mn)/255;if(l>180&&chrom<.22){wr+=r;wg+=g;wb+=b;wc++;if(r>b+5||g>b+6)warm++}}const avg=sum/Math.max(1,n),sd=Math.sqrt(Math.max(0,sum2/Math.max(1,n)-avg*avg));const pct=p=>{let t=n*p,a=0;for(let i=0;i<256;i++){a+=hist[i];if(a>=t)return i}return p<.5?0:255};const bp=pct(.01),wl=pct(.995),wp=wc?[wr/wc,wg/wc,wb/wc]:[wl,wl,wl];let cast='neutral';if(wp[0]-wp[2]>8||wp[1]-wp[2]>8)cast='warm/gelblich';else if(wp[0]-wp[2]<-8)cast='kühl/cyan';else if(wp[1]>wp[0]+8)cast='grünlich';else if(wp[0]>wp[1]+10)cast='magenta/rot';return{width:ow,height:oh,avg,sd,blackPoint:bp,whiteLuma:wl,whitePoint:wp,cast,beigeRisk:wc>20&&warm/Math.max(1,wc)>.45&&wp[2]<245,hist}}
function analyzeAndShow(j){j.analysis=analyzeCanvas(j.original);const a=j.analysis;els.analysisText.innerHTML=`Auflösung: <b>${a.width}×${a.height}</b><br>Licht: ${a.avg<85?'dunkel':a.avg>185?'hell':'ausgewogen'}<br>Kontrast: ${a.sd<38?'flach':a.sd>72?'hoch':'normal'}<br>Weißpunkt: RGB ${a.whitePoint.map(x=>Math.round(x)).join('/')}<br>Farbstich: ${a.cast}<br>Beige-Off-White: <b>${a.beigeRisk?'wahrscheinlich':'gering'}</b><br>Schwarzpunkt: ${a.blackPoint} • Weiß-Luma: ${a.whiteLuma}`}
function drawHistogram(canvas){const c=els.histogram,x=c.getContext('2d');x.clearRect(0,0,c.width,c.height);const a=analyzeCanvas(canvas),m=Math.max(...a.hist)||1;x.globalAlpha=.9;x.fillStyle='#dfe7ef';for(let i=0;i<256;i++){const h=a.hist[i]/m*c.height;x.fillRect(i/256*c.width,c.height-h,Math.max(1,c.width/256),h)}x.globalAlpha=1}

function readSettings(){const s={mode:$('#mode').value,upscale:Number($('#upscale').value),customWidth:Number($('#customWidth').value)||0,faceEnhance:$('#faceEnhance').checked,preserveText:$('#preserveText').checked};for(const id of adjustmentIds)s[id]=Number($('#'+id).value);return s}
function tunedSettings(raw){const p={photo:{white:.9,vib:.85,sat:.8,contrast:.9,denoise:1,sharpen:.9},product:{white:1.12,vib:1,sat:.9,contrast:1.08,denoise:.8,sharpen:1.08},ai:{white:1,vib:1,sat:1,contrast:1,denoise:1,sharpen:1},portrait:{white:.82,vib:.72,sat:.65,contrast:.82,denoise:1.12,sharpen:.68},graphic:{white:1.08,vib:.9,sat:.78,contrast:1.15,denoise:.35,sharpen:1.25}}[raw.mode]||{};const s={...raw};s.whiteStrength=clamp(raw.whiteStrength*(p.white||1),0,100);s.vibrance=clamp(raw.vibrance*(p.vib||1),-100,100);s.saturation=clamp(raw.saturation*(p.sat||1),-100,100);s.contrast=clamp(raw.contrast*(p.contrast||1),-100,100);s.denoise=clamp(raw.denoise*(p.denoise||1),0,100);s.sharpen=clamp(raw.sharpen*(p.sharpen||1),0,100);return s}

els.runAuto.onclick=()=>processCurrent();els.runBatch.onclick=()=>processAll();
async function processCurrent(){if(state.busy)return;const j=currentJob();if(!j)return setStatus('Bitte zuerst ein Bild laden.',0);setBusy(true);try{await processJob(j,readSettings(),true);setStatus('Fertig.',100)}finally{setBusy(false)}}
async function processAll(){if(state.busy||!state.jobs.length)return;setBusy(true);const s=readSettings(),start=state.currentId;let ok=0;try{for(let i=0;i<state.jobs.length;i++){const j=state.jobs[i];state.currentId=j.id;renderJobs();setStatus(`Batch ${i+1}/${state.jobs.length}: ${j.name}`,Math.round(i/state.jobs.length*100));try{await processJob(j,s,false);ok++}catch(e){warn(j,e.message)}await sleep()}state.currentId=start&&state.jobs.some(j=>j.id===start)?start:state.jobs[0].id;await selectJob(state.currentId);setStatus(`Batch fertig: ${ok}/${state.jobs.length}`,ok===state.jobs.length?100:90)}finally{setBusy(false)}}
async function processJob(j,raw,redraw=true){await ensureDecoded(j);j.warnings=[];const s=tunedSettings(raw);let c=cloneCanvas(j.original);setStatus(`Tonwerte: ${j.name}`,18);c=applyGlobal(c,j.analysis||analyzeCanvas(j.original),s);await sleep();if(s.denoise>0){setStatus(`Denoise: ${j.name}`,35);c=applyDenoise(c,s.denoise)}if(s.clarity!==0){setStatus(`Klarheit: ${j.name}`,45);c=applyClarity(c,s.clarity)}if(s.sharpen>0){setStatus(`Schärfen: ${j.name}`,55);c=applySharpen(c,s.sharpen,s.preserveText)}if(s.blur>0)c=applyBlur(c,s.blur);if(s.pixelate>0)c=applyPixelate(c,s.pixelate);if(s.vignette!==0)c=applyVignette(c,s.vignette);if(s.grain>0)c=applyGrain(c,s.grain);if(s.faceEnhance)c=await applyFaceEnhance(c,j);setStatus(`Upscale: ${j.name}`,78);c=await upscaleCanvas(c,s,j);j.working=c;j.status='fertig';j.progress=100;pushHistory(j,'Auto/Enhance');renderJobs();if(redraw){drawComparison(j);showWarnings(j);syncGeometryFields(j)}}

function applyGlobal(canvas,a,s){const x=canvas.getContext('2d',{willReadFrequently:true}),tile=768,exp=Math.pow(2,s.exposure),contrast=1+s.contrast/100,dehaze=1+s.dehaze/180,wp=Math.max(a.blackPoint+16,a.whiteLuma),gain=[252/Math.max(1,a.whitePoint[0]),252/Math.max(1,a.whitePoint[1]),252/Math.max(1,a.whitePoint[2])],ws=s.whiteStrength/100;for(let ty=0;ty<canvas.height;ty+=tile)for(let tx=0;tx<canvas.width;tx+=tile){const w=Math.min(tile,canvas.width-tx),h=Math.min(tile,canvas.height-ty),img=x.getImageData(tx,ty,w,h),d=img.data;for(let i=0;i<d.length;i+=4){if(d[i+3]===0)continue;let r=d[i],g=d[i+1],b=d[i+2];const orig=[r,g,b],lum0=(.2126*r+.7152*g+.0722*b)/255;r*=exp;g*=exp;b*=exp;r+=s.brightness*1.8;g+=s.brightness*1.8;b+=s.brightness*1.8;const levelStrength=Math.min(1,ws*.6+Math.abs(s.contrast)/160);const nr=(r-a.blackPoint)*255/(wp-a.blackPoint),ng=(g-a.blackPoint)*255/(wp-a.blackPoint),nb=(b-a.blackPoint)*255/(wp-a.blackPoint);r+= (nr-r)*levelStrength;g+=(ng-g)*levelStrength;b+=(nb-b)*levelStrength;r*=1+(gain[0]-1)*ws;g*=1+(gain[1]-1)*ws;b*=1+(gain[2]-1)*ws;const avg0=(r+g+b)/3,mx0=Math.max(r,g,b),mn0=Math.min(r,g,b),ch=(mx0-mn0)/255,near=Math.max(0,Math.min(1,(avg0/255-.66)/.28))*Math.max(0,Math.min(1,(.22-ch)/.18));const warm=Math.max(0,((r-b)+(g-b)*.75)/80),neutral=near*ws*Math.min(1,.35+warm);if(neutral>0){const n=Math.min(255,avg0+(255-avg0)*.2*ws);r=r*(1-neutral)+n*neutral;g=g*(1-neutral)+n*neutral;b=b*(1-neutral)+n*neutral}r*=1+s.temperature*.0013;b*=1-s.temperature*.0015;g*=1-s.temperature*.00015;r*=1+s.tint*.0007;b*=1+s.tint*.0007;g*=1-s.tint*.001;let lum=(.2126*r+.7152*g+.0722*b)/255;const sh=s.shadows/100*Math.pow(1-lum,2)*58,hi=s.highlights/100*Math.pow(lum,2)*58;r+=sh+hi;g+=sh+hi;b+=sh+hi;const whiteBoost=s.whites/100*Math.pow(lum,3)*45,blackBoost=s.blacks/100*Math.pow(1-lum,3)*45;r+=whiteBoost+blackBoost;g+=whiteBoost+blackBoost;b+=whiteBoost+blackBoost;r=(r-127.5)*contrast*dehaze+127.5;g=(g-127.5)*contrast*dehaze+127.5;b=(b-127.5)*contrast*dehaze+127.5;const gamma=1/Math.max(.1,s.gamma);r=255*Math.pow(clamp(r)/255,gamma);g=255*Math.pow(clamp(g)/255,gamma);b=255*Math.pow(clamp(b)/255,gamma);if(s.hue!==0){[r,g,b]=rotateHue(r,g,b,s.hue)}const avg=(r+g+b)/3,mx=Math.max(r,g,b),mn=Math.min(r,g,b),curSat=(mx-mn)/Math.max(1,mx),v=1+s.vibrance/100*(1-curSat)+s.saturation/100;r=avg+(r-avg)*v;g=avg+(g-avg)*v;b=avg+(b-avg)*v;if(s.dehaze!==0){const sat=1+s.dehaze/220;r=avg+(r-avg)*sat;g=avg+(g-avg)*sat;b=avg+(b-avg)*sat}d[i]=clamp(r);d[i+1]=clamp(g);d[i+2]=clamp(b)}x.putImageData(img,tx,ty)}return canvas}
function rotateHue(r,g,b,deg){const a=deg*Math.PI/180,c=Math.cos(a),s=Math.sin(a),m=[.213+c*.787-s*.213,.715-c*.715-s*.715,.072-c*.072+s*.928,.213-c*.213+s*.143,.715+c*.285+s*.140,.072-c*.072-s*.283,.213-c*.213-s*.787,.715-c*.715+s*.715,.072+c*.928+s*.072];return[clamp(r*m[0]+g*m[1]+b*m[2]),clamp(r*m[3]+g*m[4]+b*m[5]),clamp(r*m[6]+g*m[7]+b*m[8])]} 
function applyDenoise(c,str){const blur=Math.min(2.5,.25+str/35),alpha=Math.min(.52,str/140),tmp=cloneCanvas(c),tx=tmp.getContext('2d');tx.clearRect(0,0,tmp.width,tmp.height);tx.filter=`blur(${blur}px)`;tx.drawImage(c,0,0);tx.filter='none';const x=c.getContext('2d');x.save();x.globalAlpha=alpha;x.drawImage(tmp,0,0);x.restore();return c}
function applyClarity(c,str){if(!str)return c;const blur=cloneCanvas(c),bx=blur.getContext('2d');bx.clearRect(0,0,blur.width,blur.height);bx.filter='blur(2px)';bx.drawImage(c,0,0);bx.filter='none';const x=c.getContext('2d',{willReadFrequently:true}),bctx=blur.getContext('2d',{willReadFrequently:true}),amt=str/100*.8,tile=768;for(let y=0;y<c.height;y+=tile)for(let xx=0;xx<c.width;xx+=tile){const w=Math.min(tile,c.width-xx),h=Math.min(tile,c.height-y),a=x.getImageData(xx,y,w,h),b=bctx.getImageData(xx,y,w,h),d=a.data,bd=b.data;for(let i=0;i<d.length;i+=4)for(let k=0;k<3;k++)d[i+k]=clamp(d[i+k]+(d[i+k]-bd[i+k])*amt);x.putImageData(a,xx,y)}return c}
function applySharpen(c,str,preserve){const w=c.width,h=c.height;if(w*h>48_000_000&&str>55)str=55;const amt=str/100*(preserve?1.0:1.3),src=cloneCanvas(c),sx=src.getContext('2d',{willReadFrequently:true}),x=c.getContext('2d',{willReadFrequently:true}),tile=768;for(let ty=0;ty<h;ty+=tile)for(let tx=0;tx<w;tx+=tile){const ox=Math.max(0,tx-1),oy=Math.max(0,ty-1),ex=Math.min(w,tx+tile+1),ey=Math.min(h,ty+tile+1),tw=ex-ox,th=ey-oy,img=sx.getImageData(ox,oy,tw,th),out=new ImageData(new Uint8ClampedArray(img.data),tw,th),d=img.data,o=out.data;for(let yy=1;yy<th-1;yy++)for(let xx=1;xx<tw-1;xx++){const i=(yy*tw+xx)*4;if(d[i+3]===0)continue;for(let k=0;k<3;k++){const bl=(d[i-tw*4+k]+d[i+tw*4+k]+d[i-4+k]+d[i+4+k]+d[i+k]*4)/8;o[i+k]=clamp(d[i+k]+(d[i+k]-bl)*amt)}}const cx=tx-ox,cy=ty-oy,cw=Math.min(tile,w-tx),ch=Math.min(tile,h-ty);x.putImageData(out,ox,oy,cx,cy,cw,ch)}return c}
function applyBlur(c,str){const out=document.createElement('canvas');out.width=c.width;out.height=c.height;const x=out.getContext('2d');x.filter=`blur(${str}px)`;x.drawImage(c,0,0);return out}
function applyPixelate(c,v){const block=Math.max(1,Math.round(v/2));if(block<2)return c;const sw=Math.max(1,Math.round(c.width/block)),sh=Math.max(1,Math.round(c.height/block)),small=document.createElement('canvas');small.width=sw;small.height=sh;small.getContext('2d').drawImage(c,0,0,sw,sh);const out=document.createElement('canvas');out.width=c.width;out.height=c.height;const x=out.getContext('2d');x.imageSmoothingEnabled=false;x.drawImage(small,0,0,c.width,c.height);return out}
function applyVignette(c,v){const x=c.getContext('2d'),g=x.createRadialGradient(c.width/2,c.height/2,Math.min(c.width,c.height)*.18,c.width/2,c.height/2,Math.max(c.width,c.height)*.72);if(v<0){g.addColorStop(0,'rgba(0,0,0,0)');g.addColorStop(1,`rgba(0,0,0,${Math.min(.85,-v/120)})`)}else{g.addColorStop(0,'rgba(255,255,255,0)');g.addColorStop(1,`rgba(255,255,255,${Math.min(.65,v/150)})`)}x.save();x.fillStyle=g;x.fillRect(0,0,c.width,c.height);x.restore();return c}
function applyGrain(c,v){const x=c.getContext('2d',{willReadFrequently:true}),amt=v*.7,tile=768;for(let y=0;y<c.height;y+=tile)for(let xx=0;xx<c.width;xx+=tile){const w=Math.min(tile,c.width-xx),h=Math.min(tile,c.height-y),img=x.getImageData(xx,y,w,h),d=img.data;for(let i=0;i<d.length;i+=4){const n=(Math.random()-.5)*amt;d[i]=clamp(d[i]+n);d[i+1]=clamp(d[i+1]+n);d[i+2]=clamp(d[i+2]+n)}x.putImageData(img,xx,y)}return c}
async function applyFaceEnhance(c,j){if(!('FaceDetector'in window)){warn(j,'Face Enhance ist in diesem Browser nicht verfügbar.');return c}try{const det=new FaceDetector({fastMode:true,maxDetectedFaces:10}),faces=await det.detect(c),base=c.getContext('2d');for(const f of faces){const b=f.boundingBox,p=Math.max(4,Math.round(Math.max(b.width,b.height)*.12)),sx=Math.max(0,Math.floor(b.x-p)),sy=Math.max(0,Math.floor(b.y-p)),w=Math.min(c.width-sx,Math.ceil(b.width+p*2)),h=Math.min(c.height-sy,Math.ceil(b.height+p*2)),patch=document.createElement('canvas');patch.width=w;patch.height=h;patch.getContext('2d').drawImage(c,sx,sy,w,h,0,0,w,h);applySharpen(patch,16,true);base.drawImage(patch,sx,sy)}return c}catch{warn(j,'Face Enhance konnte nicht ausgeführt werden.');return c}}
async function upscaleCanvas(c,s,j){let tw=s.customWidth>0?s.customWidth:Math.round(c.width*s.upscale),th=Math.round(c.height*(tw/c.width));if(tw*th>state.safeMaxPixels||tw>state.safeMaxDimension||th>state.safeMaxDimension){const scale=Math.min(Math.sqrt(state.safeMaxPixels/(c.width*c.height)),state.safeMaxDimension/c.width,state.safeMaxDimension/c.height),safe=Math.max(1,Math.floor(scale*100)/100);tw=Math.max(c.width,Math.floor(c.width*safe));th=Math.max(c.height,Math.floor(c.height*safe));warn(j,`Upscale wurde auf ${tw}×${th}px begrenzt, um Browser-Abstürze zu vermeiden.`)}if(tw<=c.width&&th<=c.height)return c;let cur=c;while(cur.width<tw||cur.height<th){const nw=Math.min(tw,Math.max(cur.width+1,Math.round(cur.width*1.5))),nh=Math.min(th,Math.max(cur.height+1,Math.round(cur.height*1.5))),next=document.createElement('canvas');next.width=nw;next.height=nh;const x=next.getContext('2d');x.imageSmoothingEnabled=true;x.imageSmoothingQuality=s.preserveText?'medium':'high';x.drawImage(cur,0,0,nw,nh);cur=next;await sleep()}return cur}

function mutate(label,fn){const j=currentJob();if(!j?.working)return;try{const next=fn(j.working);if(next)j.working=next;afterMutation(j,label,true)}catch(e){warn(j,e.message);showWarnings(j);setStatus(`Fehler: ${e.message}`,0)}}
function afterMutation(j,label,push=true){j.status='bearbeitet';j.progress=100;if(push)pushHistory(j,label);drawComparison(j);syncGeometryFields(j);renderJobs();setStatus(label,100)}
$('#rotateLeft').onclick=()=>mutate('90° links',c=>rotate90(c,-1));$('#rotateRight').onclick=()=>mutate('90° rechts',c=>rotate90(c,1));$('#flipH').onclick=()=>mutate('Horizontal gespiegelt',c=>flipCanvas(c,true));$('#flipV').onclick=()=>mutate('Vertikal gespiegelt',c=>flipCanvas(c,false));
function rotate90(c,dir){const o=document.createElement('canvas');o.width=c.height;o.height=c.width;const x=o.getContext('2d');x.translate(o.width/2,o.height/2);x.rotate(dir*Math.PI/2);x.drawImage(c,-c.width/2,-c.height/2);return o}
function flipCanvas(c,h){const o=document.createElement('canvas');o.width=c.width;o.height=c.height;const x=o.getContext('2d');x.translate(h?c.width:0,h?0:c.height);x.scale(h?-1:1,h?1:-1);x.drawImage(c,0,0);return o}
$('#applyRotate').onclick=()=>{const a=Number($('#rotateAngle').value)||0;if(!a)return;mutate(`Begradigt ${a}°`,c=>rotateArbitrary(c,a))};
function rotateArbitrary(c,deg){const r=deg*Math.PI/180,cos=Math.abs(Math.cos(r)),sin=Math.abs(Math.sin(r)),w=Math.ceil(c.width*cos+c.height*sin),h=Math.ceil(c.width*sin+c.height*cos),o=document.createElement('canvas');o.width=w;o.height=h;const x=o.getContext('2d');x.translate(w/2,h/2);x.rotate(r);x.drawImage(c,-c.width/2,-c.height/2);return o}
$('#applyCrop').onclick=()=>mutate('Zugeschnitten',c=>cropCanvas(c));
function cropCanvas(c){const ratio=$('#cropRatio').value;if(ratio!=='free'){const [rw,rh]=ratio.split(':').map(Number),target=rw/rh,cur=c.width/c.height;let w=c.width,h=c.height;if(cur>target)w=Math.round(h*target);else h=Math.round(w/target);return cropRect(c,Math.round((c.width-w)/2),Math.round((c.height-h)/2),w,h)}const x=Math.round(c.width*Number($('#cropX').value)/100),y=Math.round(c.height*Number($('#cropY').value)/100),w=Math.min(c.width-x,Math.round(c.width*Number($('#cropW').value)/100)),h=Math.min(c.height-y,Math.round(c.height*Number($('#cropH').value)/100));if(w<1||h<1)throw new Error('Ungültiger Crop.');return cropRect(c,x,y,w,h)}
function cropRect(c,x,y,w,h){const o=document.createElement('canvas');o.width=w;o.height=h;o.getContext('2d').drawImage(c,x,y,w,h,0,0,w,h);return o}
function syncGeometryFields(j){if(!j?.working)return;$('#resizeW').value=j.working.width;$('#resizeH').value=j.working.height;updatePrintInfo(j.working.width,j.working.height)}
let resizeLock=false;$('#resizeW').oninput=()=>{if(!$('#lockRatio').checked||resizeLock)return;const j=currentJob();if(!j)return;resizeLock=true;$('#resizeH').value=Math.max(1,Math.round(Number($('#resizeW').value)*j.working.height/j.working.width));resizeLock=false};$('#resizeH').oninput=()=>{if(!$('#lockRatio').checked||resizeLock)return;const j=currentJob();if(!j)return;resizeLock=true;$('#resizeW').value=Math.max(1,Math.round(Number($('#resizeH').value)*j.working.width/j.working.height));resizeLock=false};
$('#applyResize').onclick=()=>mutate('Größe geändert',c=>resizeCanvas(c,Number($('#resizeW').value),Number($('#resizeH').value)));function resizeCanvas(c,w,h){w=Math.max(1,Math.round(w));h=Math.max(1,Math.round(h));if(w*h>state.safeMaxPixels||w>state.safeMaxDimension||h>state.safeMaxDimension)throw new Error('Zielgröße überschreitet das sichere Browser-Limit.');const o=document.createElement('canvas');o.width=w;o.height=h;const x=o.getContext('2d');x.imageSmoothingEnabled=true;x.imageSmoothingQuality='high';x.drawImage(c,0,0,w,h);return o}
$('#applyPadding').onclick=()=>mutate('Canvas erweitert',c=>paddingCanvas(c,Number($('#paddingPx').value)||0,$('#paddingColor').value));function paddingCanvas(c,p,col){if(p<=0)return c;const o=document.createElement('canvas');o.width=c.width+p*2;o.height=c.height+p*2;const x=o.getContext('2d');x.fillStyle=col;x.fillRect(0,0,o.width,o.height);x.drawImage(c,p,p);return o}

function edgeMask(c,tol){const w=c.width,h=c.height,n=w*h,x=c.getContext('2d',{willReadFrequently:true}),d=x.getImageData(0,0,w,h).data,s=[];const take=(px,py)=>{const i=(py*w+px)*4;if(d[i+3])s.push([d[i],d[i+1],d[i+2]])},st=Math.max(1,Math.floor(Math.min(w,h)/80));for(let px=0;px<w;px+=st){take(px,0);take(px,h-1)}for(let py=0;py<h;py+=st){take(0,py);take(w-1,py)}if(!s.length)return new Uint8Array(n);s.sort((a,b)=>(a[0]+a[1]+a[2])-(b[0]+b[1]+b[2]));const m=s[Math.floor(s.length/2)],mask=new Uint8Array(n),vis=new Uint8Array(n),q=new Int32Array(n);let head=0,tail=0;const en=i=>{if(!vis[i]){vis[i]=1;q[tail++]=i}};for(let px=0;px<w;px++){en(px);en((h-1)*w+px)}for(let py=0;py<h;py++){en(py*w);en(py*w+w-1)}while(head<tail){const p=q[head++],i=p*4,dist=Math.hypot(d[i]-m[0],d[i+1]-m[1],d[i+2]-m[2]);if(dist>tol)continue;mask[p]=1;const px=p%w,py=(p/w)|0;if(px>0)en(p-1);if(px<w-1)en(p+1);if(py>0)en(p-w);if(py<h-1)en(p+w)}return mask}
$('#removeBgNow').onclick=()=>mutate('Hintergrund entfernt',c=>removeBackground(c));function removeBackground(c){if(c.width*c.height>12_000_000)throw new Error('Hintergrundentfernung ist für dieses Bild zu groß. Bitte vorher verkleinern oder auf 1×/2× arbeiten.');const tol=Number($('#bgTolerance').value),mask=edgeMask(c,tol),o=cloneCanvas(c),x=o.getContext('2d',{willReadFrequently:true}),img=x.getImageData(0,0,o.width,o.height),d=img.data,mode=$('#bgMode').value,col=hex($('#bgColor').value);for(let p=0;p<mask.length;p++)if(mask[p]){const i=p*4;if(mode==='transparent')d[i+3]=0;else{d[i]=mode==='white'?255:col[0];d[i+1]=mode==='white'?255:col[1];d[i+2]=mode==='white'?255:col[2];d[i+3]=255}}x.putImageData(img,0,0);return o}
$('#blurBgNow').onclick=()=>mutate('Hintergrund weichgezeichnet',c=>blurBackground(c));function blurBackground(c){if(c.width*c.height>12_000_000)throw new Error('Hintergrund-Blur ist für dieses Bild zu groß. Bitte vorher verkleinern.');const mask=edgeMask(c,Number($('#bgTolerance').value)),blur=applyBlur(cloneCanvas(c),8),o=cloneCanvas(c),ox=o.getContext('2d',{willReadFrequently:true}),bx=blur.getContext('2d',{willReadFrequently:true}),a=ox.getImageData(0,0,o.width,o.height),b=bx.getImageData(0,0,o.width,o.height);for(let p=0;p<mask.length;p++)if(mask[p]){const i=p*4;a.data[i]=b.data[i];a.data[i+1]=b.data[i+1];a.data[i+2]=b.data[i+2]}ox.putImageData(a,0,0);return o}
function hex(h){return[parseInt(h.slice(1,3),16),parseInt(h.slice(3,5),16),parseInt(h.slice(5,7),16)]}

$$('.tool').forEach(b=>b.onclick=()=>{state.tool=b.dataset.tool;state.cloneSource=null;$$('.tool').forEach(x=>x.classList.toggle('active',x===b));setStatus(state.tool==='clone'?'Clone aktiv – Alt/Option + Klick setzt Quelle.':`Werkzeug: ${state.tool}`,0)});
function canvasPoint(e){const r=els.after.getBoundingClientRect();return{x:(e.clientX-r.left)*els.after.width/r.width,y:(e.clientY-r.top)*els.after.height/r.height}}
els.after.addEventListener('pointerdown',e=>{const j=currentJob();if(!j?.working||state.tool==='none')return;e.preventDefault();const p=canvasPoint(e);if(state.tool==='clone'&&e.altKey){state.cloneSource=p;setStatus(`Clone-Quelle: ${Math.round(p.x)}, ${Math.round(p.y)}`,0);return}state.stroke={base:cloneCanvas(j.working),last:p};els.after.setPointerCapture(e.pointerId);applyBrush(j,p,true)});
els.after.addEventListener('pointermove',e=>{if(!state.stroke||state.tool==='none')return;applyBrush(currentJob(),canvasPoint(e),false)});
for(const ev of ['pointerup','pointercancel'])els.after.addEventListener(ev,e=>{const j=currentJob();if(!state.stroke||!j)return;state.stroke=null;pushHistory(j,`Retusche: ${state.tool}`);drawComparison(j);renderJobs()});
function applyBrush(j,p,first){if(!j?.working)return;const r=Number($('#brushSize').value),hard=Number($('#brushHardness').value)/100,x=j.working.getContext('2d'),base=state.stroke.base;const pts=[];const a=state.stroke.last||p,dist=Math.hypot(p.x-a.x,p.y-a.y),steps=Math.max(1,Math.ceil(dist/Math.max(2,r*.25)));for(let s=1;s<=steps;s++)pts.push({x:a.x+(p.x-a.x)*s/steps,y:a.y+(p.y-a.y)*s/steps});for(const q of pts){if(state.tool==='erase'){x.save();x.globalCompositeOperation='destination-out';softDot(x,q.x,q.y,r,hard,'rgba(0,0,0,1)');x.restore()}else if(state.tool==='restore'){const sx=q.x*j.original.width/j.working.width,sy=q.y*j.original.height/j.working.height;copyCircle(x,j.original,sx,sy,q.x,q.y,r,hard)}else if(state.tool==='clone'){if(!state.cloneSource){setStatus('Clone: erst Alt/Option + Klick auf die Quelle.',0);break}const dx=q.x-(state.stroke.startX??p.x),dy=q.y-(state.stroke.startY??p.y);if(state.stroke.startX==null){state.stroke.startX=p.x;state.stroke.startY=p.y}copyCircle(x,base,state.cloneSource.x+dx,state.cloneSource.y+dy,q.x,q.y,r,hard)}else if(state.tool==='heal'){healDot(j.working,q.x,q.y,r,hard)}}state.stroke.last=p;drawComparison(j,false)}
function softDot(ctx,x,y,r,hard,color){const g=ctx.createRadialGradient(x,y,r*hard,x,y,r);g.addColorStop(0,color);g.addColorStop(1,'rgba(0,0,0,0)');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill()}
function copyCircle(ctx,src,sx,sy,dx,dy,r,hard){ctx.save();ctx.beginPath();ctx.arc(dx,dy,r,0,Math.PI*2);ctx.clip();ctx.globalAlpha=.35+.65*hard;ctx.drawImage(src,sx-r,sy-r,r*2,r*2,dx-r,dy-r,r*2,r*2);ctx.restore()}
function healDot(c,x,y,r,hard){const ctx=c.getContext('2d'),tmp=document.createElement('canvas');tmp.width=r*2;tmp.height=r*2;const tx=tmp.getContext('2d');tx.filter=`blur(${Math.max(2,r*.12)}px)`;tx.drawImage(c,x-r,y-r,r*2,r*2,0,0,r*2,r*2);tx.filter='none';ctx.save();ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.clip();ctx.globalAlpha=.25+.45*hard;ctx.drawImage(tmp,x-r,y-r);ctx.restore()}

$$('.filterBtn').forEach(b=>b.onclick=()=>mutate(`Filter: ${b.dataset.filter}`,c=>applyFilter(c,b.dataset.filter)));function applyFilter(c,f){if(f==='none')return c;const x=c.getContext('2d',{willReadFrequently:true}),tile=768;for(let y=0;y<c.height;y+=tile)for(let xx=0;xx<c.width;xx+=tile){const w=Math.min(tile,c.width-xx),h=Math.min(tile,c.height-y),img=x.getImageData(xx,y,w,h),d=img.data;for(let i=0;i<d.length;i+=4){let r=d[i],g=d[i+1],b=d[i+2];if(f==='bw'){const l=.2126*r+.7152*g+.0722*b;r=g=b=l}else if(f==='sepia'){const nr=.393*r+.769*g+.189*b,ng=.349*r+.686*g+.168*b,nb=.272*r+.534*g+.131*b;r=nr;g=ng;b=nb}else if(f==='warm'){r*=1.08;g*=1.025;b*=.94}else if(f==='cool'){r*=.95;g*=1.01;b*=1.08}else if(f==='vivid'){const a=(r+g+b)/3;r=a+(r-a)*1.25;g=a+(g-a)*1.25;b=a+(b-a)*1.25;r=(r-127)*1.08+127;g=(g-127)*1.08+127;b=(b-127)*1.08+127}d[i]=clamp(r);d[i+1]=clamp(g);d[i+2]=clamp(b)}x.putImageData(img,xx,y)}return c}
$('#applyOutline').onclick=()=>mutate('Sticker-Kontur',c=>outlineCanvas(c,Number($('#outlinePx').value),$('#outlineColor').value));function outlineCanvas(c,r,col){if(r<=0)return c;const o=document.createElement('canvas');o.width=c.width+r*2;o.height=c.height+r*2,mask=document.createElement('canvas');mask.width=c.width;mask.height=c.height;const mx=mask.getContext('2d');mx.drawImage(c,0,0);mx.globalCompositeOperation='source-in';mx.fillStyle=col;mx.fillRect(0,0,mask.width,mask.height);const x=o.getContext('2d'),steps=Math.max(12,Math.ceil(r*2.5));for(let rr=Math.max(1,r*.35);rr<=r;rr+=Math.max(1,r/4))for(let i=0;i<steps;i++){const a=i/steps*Math.PI*2;x.drawImage(mask,r+Math.cos(a)*rr,r+Math.sin(a)*rr)}x.drawImage(c,r,r);return o}
$('#applyFrame').onclick=()=>mutate('Rahmen',c=>paddingCanvas(c,Number($('#framePx').value),$('#frameColor').value));
$('#addText').onclick=()=>mutate('Text/Wasserzeichen',c=>addTextToCanvas(c));function addTextToCanvas(c){const t=$('#textValue').value.trim();if(!t)return c;const o=cloneCanvas(c),x=o.getContext('2d'),sz=Number($('#textSize').value)||64,col=$('#textColor').value,pos=$('#textPosition').value,pad=Math.max(12,sz*.35);x.font=`700 ${sz}px system-ui,sans-serif`;x.fillStyle=col;x.strokeStyle='rgba(0,0,0,.65)';x.lineWidth=Math.max(1,sz*.05);x.textBaseline='middle';let xx=o.width/2,yy=o.height/2,align='center';if(pos==='top')yy=pad+sz/2;if(pos==='bottom')yy=o.height-pad-sz/2;if(pos==='tl'){xx=pad;yy=pad+sz/2;align='left'}if(pos==='br'){xx=o.width-pad;yy=o.height-pad-sz/2;align='right'}x.textAlign=align;x.strokeText(t,xx,yy);x.fillText(t,xx,yy);return o}

function updatePrintInfo(w,h){const dpi=Number($('#printDpi')?.value)||300;els.printInfo.innerHTML=`${w}×${h}px → <b>${(w/dpi*2.54).toFixed(1)} × ${(h/dpi*2.54).toFixed(1)} cm</b> bei ${dpi} DPI`}
$('#printDpi').oninput=()=>{const j=currentJob();if(j)updatePrintInfo(j.working.width,j.working.height)};
$$('.printPreset').forEach(b=>b.onclick=()=>{const [w,h]=b.dataset.cm.split(',');$('#printCmW').value=w;$('#printCmH').value=h});
$('#applyPrintSize').onclick=()=>{const dpi=Number($('#printDpi').value)||300,w=Math.round(Number($('#printCmW').value)/2.54*dpi),h=Math.round(Number($('#printCmH').value)/2.54*dpi);mutate(`Print ${dpi} DPI`,c=>resizeCanvas(c,w,h))};

els.resetCurrent.onclick=()=>{const j=currentJob();if(!j?.original)return;j.working=cloneCanvas(j.original);j.history=[];j.historyIndex=-1;j.warnings=[];pushHistory(j,'Original',true);afterMutation(j,'Auf Original zurückgesetzt',false)};
els.clearJobs.onclick=()=>{state.jobs=[];state.currentId=null;renderJobs();els.canvasScroller.hidden=true;els.compareSlider.disabled=true;els.currentName.textContent='Kein Bild ausgewählt';els.currentMeta.textContent='';els.analysisText.textContent='Noch keine Analyse.';els.warningText.textContent='';els.printInfo.textContent='—';setStatus('Bereit.',0);updateHistoryButtons()};
els.downloadOriginal.onclick=()=>{const j=currentJob();if(!j)return;const a=document.createElement('a');a.href=URL.createObjectURL(j.file);a.download=j.file.name;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1500)};

async function canvasToBlob(c,format,q=1,dpi=300){if(format==='tiff'){if(!window.UTIF)throw new Error('TIFF-Encoder nicht geladen.');const x=c.getContext('2d',{willReadFrequently:true}),rgba=x.getImageData(0,0,c.width,c.height).data,buf=UTIF.encodeImage(rgba,c.width,c.height);return new Blob([buf],{type:'image/tiff'})}const mime={png:'image/png',jpeg:'image/jpeg',webp:'image/webp',avif:'image/avif'}[format]||'image/png',source=format==='jpeg'?opaqueWhite(c):c,blob=await new Promise(res=>source.toBlob(res,mime,q));if(!blob)throw new Error(`${format.toUpperCase()} wird von diesem Browser nicht unterstützt.`);if(blob.type!==mime)throw new Error(`${format.toUpperCase()}-Codec nicht verfügbar (Browser lieferte ${blob.type||'unbekannt'}).`);return format==='png'&&dpi?await addPngDpi(blob,dpi):blob}
function opaqueWhite(c){const o=document.createElement('canvas');o.width=c.width;o.height=c.height;const x=o.getContext('2d');x.fillStyle='#fff';x.fillRect(0,0,o.width,o.height);x.drawImage(c,0,0);return o}
async function addPngDpi(blob,dpi){try{const a=new Uint8Array(await blob.arrayBuffer());if(String.fromCharCode(...a.slice(1,4))!=='PNG')return blob;const ppm=Math.round(dpi/0.0254),data=new Uint8Array(9);new DataView(data.buffer).setUint32(0,ppm);new DataView(data.buffer).setUint32(4,ppm);data[8]=1;const type=new TextEncoder().encode('pHYs'),crcIn=new Uint8Array(type.length+data.length);crcIn.set(type);crcIn.set(data,type.length);const chunk=new Uint8Array(4+4+9+4),dv=new DataView(chunk.buffer);dv.setUint32(0,9);chunk.set(type,4);chunk.set(data,8);dv.setUint32(17,crc32(crcIn));const ihdrEnd=8+4+4+13+4,out=new Uint8Array(a.length+chunk.length);out.set(a.slice(0,ihdrEnd));out.set(chunk,ihdrEnd);out.set(a.slice(ihdrEnd),ihdrEnd+chunk.length);return new Blob([out],{type:'image/png'})}catch{return blob}}
function crc32(bytes){let c=0xffffffff;for(const b of bytes){c^=b;for(let k=0;k<8;k++)c=(c>>>1)^(0xedb88320&-(c&1))}return(c^0xffffffff)>>>0}
function ext(f){return({jpeg:'jpg',tiff:'tiff',png:'png',webp:'webp',avif:'avif'})[f]||f}
async function exportFor(j){if(!j?.working)throw new Error('Kein Ergebnis vorhanden.');const f=els.exportFormat.value,q=Number(els.exportQuality.value)/100,dpi=Number(els.exportDpi.value)||300,b=await canvasToBlob(j.working,f,q,dpi);return{blob:b,name:`${baseName(j.name)}_HP67.${ext(f)}`}}
function downloadBlob(b,n){const a=document.createElement('a');a.href=URL.createObjectURL(b);a.download=n;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1800)}
els.exportFormat.onchange=()=>{const f=els.exportFormat.value;els.exportNotice.textContent=f==='png'?'PNG: verlustfrei, Alpha + DPI-Metadaten.':f==='tiff'?'TIFF: verlustfrei, hoher RAM-Bedarf.':f==='jpeg'?'JPG: keine Transparenz; transparente Bereiche werden weiß.':f==='avif'?'AVIF: nur wenn der Browser den Encoder unterstützt.':'WebP: kompakt; Qualität 100 ist browserabhängig.'};
els.exportCurrent.onclick=async()=>{try{setBusy(true);setStatus('Export …',92);const r=await exportFor(currentJob());downloadBlob(r.blob,r.name);setStatus('Export fertig.',100)}catch(e){setStatus(`Exportfehler: ${e.message}`,0)}finally{setBusy(false)}};
els.exportZip.onclick=async()=>{if(!window.JSZip)return setStatus('ZIP-Bibliothek fehlt.',0);const ready=state.jobs.filter(j=>j.working);if(!ready.length)return;setBusy(true);try{const z=new JSZip();for(let i=0;i<ready.length;i++){setStatus(`ZIP ${i+1}/${ready.length}`,Math.round((i+1)/ready.length*85));const r=await exportFor(ready[i]);z.file(r.name,r.blob);await sleep()}downloadBlob(await z.generateAsync({type:'blob',compression:'DEFLATE'}),'hoodplaka67_batch.zip');setStatus('ZIP fertig.',100)}catch(e){setStatus(`ZIP-Fehler: ${e.message}`,0)}finally{setBusy(false)}};

function addSessionHistory(j,label){state.history.unshift({time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}),name:j.name,label});state.history=state.history.slice(0,30);els.historyList.innerHTML=state.history.map(x=>`<span class="history-item">${escapeHtml(x.time)} • ${escapeHtml(x.name)} • ${escapeHtml(x.label)}</span>`).join('')}
$('#saveCustomPreset').onclick=()=>{const s=readSettings();localStorage.setItem('hp67-custom-preset',JSON.stringify(s));setStatus('Eigenes Preset gespeichert.',0)};
$('#loadCustomPreset').onclick=()=>{try{const p=JSON.parse(localStorage.getItem('hp67-custom-preset')||'null');if(!p)return setStatus('Kein eigenes Preset gespeichert.',0);for(const[k,v]of Object.entries(p)){const el=$('#'+k);if(el&&typeof v!=='boolean')el.value=v;if(el&&typeof v==='boolean')el.checked=v;const out=$('#'+k+'Out');if(out)out.textContent=k==='gamma'?Number(v).toFixed(2):k==='hue'?`${v}°`:v}setStatus('Eigenes Preset geladen.',0)}catch{setStatus('Preset konnte nicht geladen werden.',0)}};

// Doppelklick auf einen Job = mit aktuellen Einstellungen verarbeiten.
els.jobList.addEventListener('dblclick',async e=>{const item=e.target.closest('.job-item');if(item){await selectJob(item.dataset.id);processCurrent()}});
})();
